version: "3.7" # version dari docker compose yang dipakai

# syntax pembuka untuk menegaskan bahwa ini memasuki bagian pendeklarasian service
services:
  # nama dari service pertama yang dideklarasi
  item-app:
    # image yang diunduh dari namespace emhando dengan repository item-app yang memiliki tag v1
    image: ghcr.io/emhandho/item-app:v1
    # bagian ekspose port, seperti yang kita tahu aplikasi dan dockerfile yang kita unduh mengekspos port 8080,
    # namun disini saya meneruskan port tersebut ke 80 sesuai dengan kriteria submission
    ports:
      - 80:8080
    # syntax yang berfungsi sesuai dengan namanya depends_on, yaitu service yang memiliki ketergantungan terhadap berjalannya service lain,
    # field ini dapat memiliki lebih dari satu nama service lain, dan service yang memiliki field ini akan dijalankan apabila
    # service dengan nama yang ada dalam field depends_on ini sudah berjalan semua
    depends_on:
      - item-db
    # pada bagian adalah field syntax yang memiliki fungsi sama dengan tag --restart pada docker run,
    # yaitu service akan selalu restart apabila service terhenti karena kesalahan yang terjadi pada container nya
    restart: always

  # nama dari service kedua yang dideklarasi
  item-db:
    # image yang dipakai untuk membangun service ini
    image: mongo:3
    # deklarasi volume yang akan di mount dengan service item-db
    volumes:
      - app-db:/data/db
    restart: always

# pendeklarasian volumes yang akan dipakai pada docker compose ini
volumes:
  app-db:
