apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    db: mongodb
    app: database
spec:
  selector:
    matchLabels:
      db: mongodb
      app: database
  serviceName: mongodb
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        db: mongodb
        app: database
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
        - name: mongodb-config
          mountPath: /config
        - name: mongodb-secret
          mountPath: /etc/mongo-credentials
        env:
        - name: MONGO_INITDB_ROOT_USERNAME_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
      volumes:
        - name: mongodb-persistent-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc
        - name: mongodb-config
          configMap:
            name: mongodb-config
        - name: mongodb-secret
          secret:
            secretName: mongo-secret          